package os.toolset.pipeline.stage;

import os.toolset.config.StageConfig;
import os.toolset.pipeline.Context;
import os.toolset.pipeline.ExecutionError;

/**
 * Stages in a pipeline represent the logical steps needed to process data.
 * Each stage represents a single high-level processing concept such as reading files, loading data from external storage, computing a product from the data, writing data to the database, etc.
 * <p>
 * Stage is supposed to be stateless. So, no information about previous processing is stored.
 */
public interface Stage<C extends Context> {

    /**
     * @return unique identifier of the stage,
     */
    String name();

    /**
     * Determines if the stage is active and execution context contains all data required for
     * the stage execution
     *
     * @return
     */
    default boolean isReady(C context) {
        return true;
    }

    /**
     * @param context pipeline execution context
     * @throws ExecutionError
     */
    void run(C context) throws ExecutionError;

    /**
     * This method will be called when the pipeline execution failed
     * and can be used to roll back some changes.
     * For example this method can be used to clean up outputs generated by the stage.
     *
     * @param context pipeline execution context
     */
    default void revertChanges(C context) {
        //do nothing by default
    }

    /**
     * This method is called if the whole pipeline execution was successful
     * and can be used to update some metadata required by this specific stage on the next run.
     * @param context pipeline execution context
     */
    default void terminate(C context) {
    }

    default StageConfig stageConfig(C context) {
        return context.pipelineConfig().stageConfig(name());
    }
}
